### ISSUE TITLE
Error: Could not find or load main class ConstituencyParse

### ISSUE THREAD

**Issue by YuanEZhou** [volkancirik/groundnet#5]
Hi @volkancirik , when I run

java -cp ../parser/:../parser/stanford-parser-full-2016-10-31/stanford-parser.jar:../parser/stanford-parser-full-2016-10-31/stanford-parser-3.7.0-models.jar  ConstituencyParse -tokpath ../parser/example.tok -parentpath ../parser/example.par -tokenize -inputpath ../parser/example.txt -bparsepath ../parser/example.bp -nparsepath ../parser/example.np

I get the following error
Error: Could not find or load main class ConstituencyParse
How to fix this?
Thanks.

**Comment by YuanEZhou** [comment]
I have bypassed it by using **stanfordcorenlp** instead of **stanford parser**.
Just replacing `java -cp ConstituencyParse` in interactiveModel.ipynb with following
`from stanfordcorenlp import StanfordCoreNLP`
`nlp = StanfordCoreNLP('../parser/stanford-corenlp-full-2018-10-05')`
`input_nl = "there is an old lady sitting on a couch biting her finger"`
`tmp = nlp.parse(input_nl)`
`l = tmp.replace('\n','')`

**Comment by volkancirik** [comment]
Sorry for late response! were you able to solve the issue?

**Comment by YuanEZhou** [comment]
yeah, thanks!

**Comment by volkancirik** [comment]
great! 

also, [this parser](https://github.com/nikitakit/self-attentive-parse) may give better results and probably faster.
